font_family      JetBrains Mono
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_trail 1

background_opacity 1.0
confirm_os_window_close 0

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no
hide_window_decorations yes

# Liberar atajos para que lleguen a nvim (p.ej. Ctrl+Tab para cambiar de buffer)
map ctrl+tab no_op
map ctrl+shift+tab no_op

window_padding_width 2

include /tmp/kitty-matugen-colors.conf

cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

background_image /home/evert/Pictures/fastfetch/seris.png
background_image_layout scaled
background_tint 0.85

# Open new tab
map ctrl+t new_tab
# Close current tab 
map ctrl+w close_tab

# New window
map alt+enter new_window
# Close current window
map alt+q close_window

# Navigate between windows using Alt + Arrow Keys
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

# Enable the design of flexible partitions
enabled_layouts splits,stack

# Open a new windows on the:
map ctrl+right launch --location=vsplit --cwd=current
map ctrl+left launch --location=vsplit --cwd=current; move_window_backward
map ctrl+down launch --location=hsplit --cwd=current
map ctrl+up launch --location=hsplit --cwd=current; move_window_to_top

# Fullsreen
map ctrl+alt+f toggle_layout stack
